version: "3.9"
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mysql

  inventory-service:
    build: ./inventory-service
    ports:
      - "3001:3001"
    env_file:
      - ./inventory-service/.env
    depends_on:
      - mysql

  delivery-service:
    build: ./delivery-service
    ports:
      - "3003:3003"
    env_file:
      - ./delivery-service/.env
    depends_on:
      - mysql

  iot-service:
    build: ./iot-service
    ports:
      - "3004:3004"
    env_file:
      - ./iot-service/.env
    depends_on:
      - mysql
      - rabbitmq

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - auth-service
      - inventory-service
      - delivery-service
      - iot-service

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    volumes:
      - ./inventory_db.sql:/docker-entrypoint-initdb.d/init.sql
