apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-service
  template:
    metadata:
      labels:
        app: iot-service
    spec:
      containers:
        - name: iot-service
          image: iot-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3004